In [85]:
import pandas as pd

# various options in pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 25)
pd.set_option('display.precision', 3)

## Data Acquisition

In [86]:
!pwd

/Users/mbarry/Documents/Coding/ds/metis/projects/02_projectluther/CPS

In [87]:
#from Chicago City data portal
!ls ./data

Chicago_Public_Schools_-_School_Profile_Information_SY1617.csv
Chicago_Public_Schools_-_School_Profile_Information_SY1718.csv
Chicago_Public_Schools_-_School_Profile_Information_SY1819.csv
Chicago_Public_Schools_-_School_Progress_Reports_SY1516.csv

In [88]:
#school_profile_201516 = pd.read_csv('data/Chicago_Public_Schools_-_School_Progress_Reports_SY1516.csv')
school_profile_201617 = pd.read_csv('data/Chicago_Public_Schools_-_School_Profile_Information_SY1617.csv')
school_profile_201718 = pd.read_csv('data/Chicago_Public_Schools_-_School_Profile_Information_SY1718.csv')
#school_profile_201819 = pd.read_csv('data/Chicago_Public_Schools_-_School_Profile_Information_SY1819.csv')

### data prep

### 2017-18

In [89]:
school_profile_201718['Is_High_School'].unique()

array(['Y', 'N'], dtype=object)

In [90]:
highschools_1718 = school_profile_201718[school_profile_201718['Is_High_School'] == 'Y']

In [91]:
len(highschools_1718)

184

In [92]:
highschools_1718['Graduation_Rate_School'].isna().sum()

60

In [93]:
highschools_1718[['School_ID', 'Long_Name']]

     School_ID                                        Long_Name
0       610592                       Englewood STEM High School
1       610591            National Teachers Academy High School
2       610506     TEAM Englewood Community Academy High School
5       400102  Urban Prep Charter Academy for Young Men - West
12      400035  Chicago Math and Science Academy Charter School
13      400139               YCCS-Sullivan House Alternative HS
14      610357                 Spry Community Links High School
16      609760     George Washington Carver Military Academy HS
18      609711                William Rainey Harper High School
24      400113                        CICS - ChicagoQuest North
27      400161                Chicago Collegiate Charter School
28      609754             Chicago Military Academy High School
..         ...                                              ...
624     400117                   Noble - Hansberry College Prep
625     610571                          Ombudsman Chicago- West
627     609730                        Nicholas Senn High School
632     400062         Perspectives - High School of Technology
636     610323                                Bowen High School
638     610394                     Uplift Community High School
645     609724                     Stephen T Mather High School
646     609715                         Thomas Kelly High School
647     400077                 University of Chicago - Woodlawn
651     609741                     Gurdon S Hubbard High School
652     610570                         Ombudsman Chicago- South
657     610390       Hyman G Rickover Naval Academy High School

[184 rows x 2 columns]

In [94]:
list(highschools_1718)

['School_ID',
 'Legacy_Unit_ID',
 'Finance_ID',
 'Short_Name',
 'Long_Name',
 'Primary_Category',
 'Is_High_School',
 'Is_Middle_School',
 'Is_Elementary_School',
 'Is_Pre_School',
 'Summary',
 'Administrator_Title',
 'Administrator',
 'Secondary_Contact_Title',
 'Secondary_Contact',
 'Phone',
 'Fax',
 'CPS_School_Profile',
 'Website',
 'Facebook',
 'Twitter',
 'Youtube',
 'Pinterest',
 'Attendance_Boundaries',
 'Grades_Offered_All',
 'Grades_Offered',
 'Student_Count_Total',
 'Student_Count_Low_Income',
 'Student_Count_Special_Ed',
 'Student_Count_English_Learners',
 'Student_Count_Black',
 'Student_Count_Hispanic',
 'Student_Count_White',
 'Student_Count_Asian',
 'Student_Count_Native_American',
 'Student_Count_Other_Ethnicity',
 'Student_Count_Asian_Pacific_Islander',
 'Student_Count_Multi',
 'Student_Count_Hawaiian_Pacific_Islander',
 'Student_Count_Ethnicity_Not_Available',
 'Statistics_Description',
 'Demographic_Description',
 'Dress_Code',
 'PreK_School_Day',
 'Kindergarten_School_Day',
 'School_Hours',
 'Freshman_Start_End_Time',
 'After_School_Hours',
 'Earliest_Drop_Off_Time',
 'Classroom_Languages',
 'Bilingual_Services',
 'Refugee_Services',
 'Title_1_Eligible',
 'PreSchool_Inclusive',
 'Preschool_Instructional',
 'Significantly_Modified',
 'Hard_Of_Hearing',
 'Visual_Impairments',
 'Transportation_Bus',
 'Transportation_El',
 'Transportation_Metra',
 'Average_ACT_School',
 'Mean_ACT',
 'College_Enrollment_Rate_School',
 'College_Enrollment_Rate_Mean',
 'Graduation_Rate_School',
 'Graduation_Rate_Mean',
 'Overall_Rating',
 'Rating_Status',
 'Rating_Statement',
 'Classification_Description',
 'School_Year',
 'Third_Contact_Title',
 'Third_Contact_Name',
 'Fourth_Contact_Title',
 'Fourth_Contact_Name',
 'Fifth_Contact_Title',
 'Fifth_Contact_Name',
 'Sixth_Contact_Title',
 'Sixth_Contact_Name',
 'Seventh_Contact_Title',
 'Seventh_Contact_Name',
 'Network',
 'Is_GoCPS_Participant',
 'Is_GoCPS_PreK',
 'Is_GoCPS_Elementary',
 'Is_GoCPS_High_School',
 'Open_For_Enrollment_Date',
 'Closed_For_Enrollment_Date',
 'School_Latitude',
 'School_Longitude',
 'Location']

### 2016-17

In [95]:
school_profile_201617['Is_High_School'].unique()

array(['N', 'Y'], dtype=object)

In [96]:
highschools_1617 = school_profile_201617[school_profile_201617['Is_High_School'] == 'Y']

In [97]:
highschools_1617['Graduation_Rate_School'].isna().sum()

63

In [98]:
highschools_1617['Zip']

10     60608
11     60639
12     60628
14     60617
19     60649
21     60607
24     60628
25     60632
29     60644
31     60637
36     60651
37     60639
       ...
619    60609
623    60622
629    60609
633    60621
636    60623
637    60609
644    60636
649    60610
651    60612
653    60612
655    60660
657    60647
Name: Zip, Length: 184, dtype: int64

### Merge

In [99]:
#take out 18/19 because income data is not readily available
school_years = [highschools_1617, highschools_1718]

In [100]:
df = pd.concat(school_years)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [101]:
len(df)

368

In [102]:
df.shape

(368, 98)

### Drop Rows

In [103]:
df = df.dropna(subset = ['Graduation_Rate_School'])

In [104]:
df[['Zip','Long_Name']]

         Zip                                        Long_Name
10   60608.0      Benito Juarez Community Academy High School
11   60639.0                    Noble - Pritzker College Prep
12   60628.0  Gwendolyn Brooks College Preparatory Academy HS
14   60617.0                 EPIC Academy Charter High School
21   60607.0               Whitney M Young Magnet High School
25   60632.0  Marie Sklodowska Curie Metropolitan High School
29   60644.0    Austin College and Career Academy High School
31   60637.0                 University of Chicago - Woodlawn
36   60651.0      Noble - Rowe-Clark Math and Science Academy
38   60640.0                     Uplift Community High School
55   60623.0         North Lawndale College Prep - Christiana
56   60620.0         Neal F Simeon Career Academy High School
..       ...                                              ...
617      NaN            North Lawndale College Prep - Collins
622      NaN                    Air Force Academy High School
624      NaN                   Noble - Hansberry College Prep
627      NaN                        Nicholas Senn High School
632      NaN         Perspectives - High School of Technology
636      NaN                                Bowen High School
638      NaN                     Uplift Community High School
645      NaN                     Stephen T Mather High School
646      NaN                         Thomas Kelly High School
647      NaN                 University of Chicago - Woodlawn
651      NaN                     Gurdon S Hubbard High School
657      NaN       Hyman G Rickover Naval Academy High School

[245 rows x 2 columns]

In [105]:
df.tail()

,ADA_Accessible,Address,Administrator,Administrator_Title,After_School_Hours,Attendance_Boundaries,Average_ACT_School,Bilingual_Services,CPS_School_Profile,City,Classification_Description,Classroom_Languages,Closed_For_Enrollment_Date,College_Enrollment_Rate_Mean,College_Enrollment_Rate_School,Demographic_Description,Dress_Code,Earliest_Drop_Off_Time,Facebook,Fax,Fifth_Contact_Name,Fifth_Contact_Title,Finance_ID,Fourth_Contact_Name,Fourth_Contact_Title,Freshman_Start_End_Time,Grades_Offered,Grades_Offered_All,Graduation_Rate_Mean,Graduation_Rate_School,Hard_Of_Hearing,Is_Elementary_School,Is_GoCPS_Elementary,Is_GoCPS_High_School,Is_GoCPS_Participant,Is_GoCPS_PreK,Is_High_School,Is_Middle_School,Is_Pre_School,Kindergarten_School_Day,Legacy_Unit_ID,Location,Long_Name,Mean_ACT,Network,Open_For_Enrollment_Date,Overall_Rating,Phone,Pinterest,PreK_School_Day,PreSchool_Inclusive,Preschool_Instructional,Primary_Category,Rating_Statement,Rating_Status,Refugee_Services,School_Hours,School_ID,School_Latitude,School_Longitude,School_Type,School_Year,Secondary_Contact,Secondary_Contact_Title,Seventh_Contact_Name,Seventh_Contact_Title,Short_Name,Significantly_Modified,Sixth_Contact_Name,Sixth_Contact_Title,State,Statistics_Description,Student_Count_Asian,Student_Count_Asian_Pacific_Islander,Student_Count_Black,Student_Count_English_Learners,Student_Count_Ethnicity_Not_Available,Student_Count_Hawaiian_Pacific_Islander,Student_Count_Hispanic,Student_Count_Low_Income,Student_Count_Multi,Student_Count_Native_American,Student_Count_Other_Ethnicity,Student_Count_Special_Ed,Student_Count_Total,Student_Count_White,Summary,Third_Contact_Name,Third_Contact_Title,Title_1_Eligible,Transportation_Bus,Transportation_El,Transportation_Metra,Twitter,Visual_Impairments,Website,Youtube,Zip
645,NaN,NaN,Peter J Auffant,Principal,3:16 PM to 6:00 PM,Y,NaN,Y,http://cps.edu/Schools/Pages/school.aspx?Schoo...,NaN,Schools that have an attendance boundary. Gene...,"French, Spanish, Spanish for Heritage Speakers",NaN,59.8,65.2,The largest demographic at MATHER HS is Hispan...,N,7:30 AM,NaN,7.735e+09,NaN,NaN,46241,NaN,NaN,8:00 AM to 3:16 PM,12-Sep,"9,10,11,12",77.5,78.5,NaN,N,N,Y,Y,N,Y,N,N,NaN,1480,"5835 N LINCOLN AVE\nChicago, Illinois 60659\n(...",Stephen T Mather High School,NaN,Network 14,9/1/04 0:00,Level 1,7.735e+09,NaN,NaN,NaN,NaN,HS,"This school received a Level 1 rating, which i...",GOOD STANDING,Y,8:00 AM to 3:16 PM,609724,41.988,-87.702,NaN,School Year 2017-2018,Julie Lyons,Assistant Principal,NaN,NaN,MATHER HS,NaN,NaN,NaN,NaN,There are 1484 students enrolled at MATHER HS....,428,0,199,394,0,7,571,782,22,10,0,222,1484,247,Mather High School is a global family in a nei...,Christina Laino,Assistant Principal,Y,"11, 84, 93","Brown, Red",NaN,https://twitter.com/Matherhs,NaN,http://www.matherhs.org,NaN,NaN
646,NaN,NaN,Raul Magdaleno,Principal,NaN,Y,NaN,Y,http://cps.edu/Schools/Pages/school.aspx?Schoo...,NaN,Schools that have an attendance boundary. Gene...,"Chinese, Spanish",NaN,59.8,54.0,The largest demographic at KELLY HS is Hispani...,N,NaN,NaN,7.735e+09,Andrew Chipman,Assistant Principal,46181,Griselda Esparza,Assistant Principal,7:45 AM-3:00 PM,12-Sep,"9,10,11,12",77.5,79.2,NaN,N,N,Y,Y,N,Y,N,N,NaN,1400,"4136 S CALIFORNIA AVE\nChicago, Illinois 60632...",Thomas Kelly High School,NaN,Network 16,9/1/04 0:00,Level 2+,7.735e+09,NaN,NaN,NaN,NaN,HS,"This school received a Level 2+ rating, which ...",GOOD STANDING,N,7:45 AM - 3:00 PM,609715,41.819,-87.695,NaN,School Year 2017-2018,Wendy Fischer,Assistant Principal,NaN,NaN,KELLY HS,NaN,NaN,NaN,NaN,There are 1901 students enrolled at KELLY HS. ...,250,2,76,533,23,2,1502,1517,8,4,0,339,1901,34,"Kelly combines selective enrollment in IB, AP,...",Liddell-Jegen McGuire,Assistant Principal,Y,"39, 62, 94",Orange,NaN,https://twitter.com/ThomasKelly_HS,NaN,http://kellyhighschool.org/,NaN,NaN
647,NaN,NaN,Mr. Kieran Palmer-Klein,Director,3:40PM -5:15PM,Y,NaN,N,http://cps.edu/Schools/Pages/school.aspx?Schoo...,NaN,"Schools that are open to all Chicago children,...",NaN,NaN,59.8,75.9,The largest demographic at U OF C - WOODLAWN H...,Y,7:30AM,https://www.facebook.com/UCCharterSchool,7.733e+09,Carla Scott,Admissions Director,66112,Latasha McMillion,Operations Manager,8:00AM - 3:40PM,12-Jun,"6,7,8,9,10,11,12",77.5,73.1,NaN,Y,N,Y,Y,N,Y,Y,N,NaN,3061,"6300 S UNIVERSITY AVE\nChicago, Illinois 60637...",University of Chicago - Woodlawn,NaN,Charter,9/1/04 0:00,Level 1,7.738e+09,NaN,NaN,NaN,NaN,HS,"This school received a Level 1 rating, which i...",NOT APPLICABLE,N,8:00AM -3:40PM,400077,41.778,-87.598,NaN,School Year 2017-2018,Sonia Wang,Middle School Director,NaN,NaN,U OF C - WOODLAWN HS,NaN,NaN,NaN,NaN,There are 623 students enrolled at U OF C - WO...,0,0,608,1,5,0,7,368,2,1,0,91,623,0,Woodlawn 100% college acceptanceÂ five consecut...,Leslie Foster-Ramsey,Assistant High School Director,Y,"63, 6",Green,Metra Electric District (ME),http://twitter.com/UCCharterSchool,NaN,http://www.uchicagocharter.org/page.cfm?p=519,http://www.youtube.com/watch?v=ZQHE1_nnaS8,NaN
651,NaN,NaN,Angelica Altamirano,Principal,03:30 PM - 7:00 PM,Y,NaN,Y,http://cps.edu/Schools/Pages/school.aspx?Schoo...,NaN,Schools that have an attendance boundary. Gene...,Spanish,NaN,59.8,57.4,The largest demographic at HUBBARD HS is Hispa...,Y,6:00 AM,NaN,7.735e+09,NaN,NaN,46341,Jean Biba-Brown,IB Coordinator,8:00 a.m. - 3:15 p.m.,12-Sep,"9,10,11,12",77.5,82.9,NaN,N,N,Y,Y,N,Y,N,N,NaN,1670,"6200 S HAMLIN AVE\nChicago, Illinois 60629\n(4...",Gurdon S Hubbard High School,NaN,Network 16,9/1/04 0:00,Level 1,7.735e+09,NaN,NaN,NaN,NaN,HS,"This school received a Level 1 rating, which i...",GOOD STANDING,N,8:00 am-4:00 pm,609741,41.781,-87.718,NaN,School Year 2017-2018,Angelica Altamirano,Assistant Principal,NaN,NaN,HUBBARD HS,NaN,NaN,NaN,NaN,There are 1705 students enrolled at HUBBARD HS...,2,0,112,297,3,0,1547,1463,3,7,0,253,1705,31,Hubbard is a diverse student and faculty commu...,Ishshah Phillips,Assistant Principal,Y,"53A, 63, 59",Orange,NaN,NaN,NaN,http://www.hubbardhighschool.org,NaN,NaN
657,NaN,NaN,Michael Jerome Biela,Principal,3:30 p.m. - 6:00 p.m.,N,NaN,N,http://cps.edu/Schools/Pages/school.aspx?Schoo...,NaN,For students who wish to develop leadership an...,"French, Spanish",NaN,59.8,62.6,The largest demographic at RICKOVER MILITARY H...,Y,7:15 a.m.,NaN,7.735e+09,NaN,NaN,45221,Beth Lanners,Counselor,8:15 a.m. - 3:20 p.m.,12-Sep,"9,10,11,12",77.5,88.3,NaN,N,N,Y,Y,N,Y,N,N,NaN,7140,"5900 N GLENWOOD AVE\nChicago, Illinois 60660\n...",Hyman G Rickover Naval Academy High School,NaN,ISP,9/1/04 0:00,Level 1,7.735e+09,NaN,NaN,NaN,NaN,HS,"This school received a Level 1 rating, which i...",GOOD STANDING,N,8:15 a.m. - 3:20 p.m.,610390,41.989,-87.666,NaN,School Year 2017-2018,Jen Narbert,Assistant Principal,NaN,NaN,RICKOVER MILITARY HS,NaN,NaN,NaN,NaN,There are 458 students enrolled at RICKOVER MI...,28,0,35,29,0,0,352,245,3,2,0,54,458,38,Rickover provides a foundation for future succ...,Jeff Rodriguez,Assistant Principal,Y,"22, 36, 84, 50",Red,NaN,NaN,NaN,http://www.rickovernaval.org,NaN,NaN

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 245 entries, 10 to 657
Data columns (total 98 columns):
ADA_Accessible                             121 non-null object
Address                                    121 non-null object
Administrator                              245 non-null object
Administrator_Title                        245 non-null object
After_School_Hours                         147 non-null object
Attendance_Boundaries                      245 non-null object
Average_ACT_School                         117 non-null float64
Bilingual_Services                         233 non-null object
CPS_School_Profile                         245 non-null object
City                                       121 non-null object
Classification_Description                 245 non-null object
Classroom_Languages                        232 non-null object
Closed_For_Enrollment_Date                 0 non-null float64
College_Enrollment_Rate_Mean               244 non-null float64
College_Enrollment_Rate_School             242 non-null float64
Demographic_Description                    245 non-null object
Dress_Code                                 245 non-null object
Earliest_Drop_Off_Time                     173 non-null object
Facebook                                   132 non-null object
Fax                                        243 non-null float64
Fifth_Contact_Name                         62 non-null object
Fifth_Contact_Title                        65 non-null object
Finance_ID                                 245 non-null int64
Fourth_Contact_Name                        105 non-null object
Fourth_Contact_Title                       107 non-null object
Freshman_Start_End_Time                    189 non-null object
Grades_Offered                             245 non-null object
Grades_Offered_All                         245 non-null object
Graduation_Rate_Mean                       245 non-null float64
Graduation_Rate_School                     245 non-null float64
Hard_Of_Hearing                            11 non-null object
Is_Elementary_School                       245 non-null object
Is_GoCPS_Elementary                        124 non-null object
Is_GoCPS_High_School                       124 non-null object
Is_GoCPS_Participant                       124 non-null object
Is_GoCPS_PreK                              124 non-null object
Is_High_School                             245 non-null object
Is_Middle_School                           245 non-null object
Is_Pre_School                              245 non-null object
Kindergarten_School_Day                    5 non-null object
Legacy_Unit_ID                             245 non-null int64
Location                                   245 non-null object
Long_Name                                  245 non-null object
Mean_ACT                                   121 non-null float64
Network                                    122 non-null object
Open_For_Enrollment_Date                   124 non-null object
Overall_Rating                             245 non-null object
Phone                                      245 non-null float64
Pinterest                                  4 non-null object
PreK_School_Day                            6 non-null object
PreSchool_Inclusive                        0 non-null object
Preschool_Instructional                    0 non-null object
Primary_Category                           245 non-null object
Rating_Statement                           245 non-null object
Rating_Status                              245 non-null object
Refugee_Services                           229 non-null object
School_Hours                               240 non-null object
School_ID                                  245 non-null int64
School_Latitude                            245 non-null float64
School_Longitude                           245 non-null float64
School_Type                                121 non-null object
School_Year                                245 non-null object
Secondary_Contact                          215 non-null object
Secondary_Contact_Title                    221 non-null object
Seventh_Contact_Name                       22 non-null object
Seventh_Contact_Title                      22 non-null object
Short_Name                                 245 non-null object
Significantly_Modified                     82 non-null object
Sixth_Contact_Name                         41 non-null object
Sixth_Contact_Title                        41 non-null object
State                                      121 non-null object
Statistics_Description                     245 non-null object
Student_Count_Asian                        245 non-null int64
Student_Count_Asian_Pacific_Islander       245 non-null int64
Student_Count_Black                        245 non-null int64
Student_Count_English_Learners             245 non-null int64
Student_Count_Ethnicity_Not_Available      245 non-null int64
Student_Count_Hawaiian_Pacific_Islander    245 non-null int64
Student_Count_Hispanic                     245 non-null int64
Student_Count_Low_Income                   245 non-null int64
Student_Count_Multi                        245 non-null int64
Student_Count_Native_American              245 non-null int64
Student_Count_Other_Ethnicity              245 non-null int64
Student_Count_Special_Ed                   245 non-null int64
Student_Count_Total                        245 non-null int64
Student_Count_White                        245 non-null int64
Summary                                    244 non-null object
Third_Contact_Name                         148 non-null object
Third_Contact_Title                        150 non-null object
Title_1_Eligible                           245 non-null object
Transportation_Bus                         232 non-null object
Transportation_El                          185 non-null object
Transportation_Metra                       67 non-null object
Twitter                                    142 non-null object
Visual_Impairments                         4 non-null object
Website                                    243 non-null object
Youtube                                    27 non-null object
Zip                                        121 non-null float64
dtypes: float64(12), int64(17), object(69)
memory usage: 189.5+ KB

In [107]:
df.info

<bound method DataFrame.info of            ADA_Accessible                Address  \
10   Generally accessible       1450 W CERMAK RD
11   Generally accessible     4131 W CORTLAND ST
12       Fully Accessible         250 E 111TH ST
14   Generally accessible     8255 S HOUSTON AVE
21   Generally accessible        211 S LAFLIN ST
25   Generally accessible      4959 S ARCHER AVE
29   Generally accessible         231 N PINE AVE
31   Generally accessible  6420 S UNIVERSITY AVE
36       Fully Accessible     3645 W CHICAGO AVE
38   Generally accessible       900 W WILSON AVE
55       Fully Accessible  1615 S CHRISTIANA AVE
56   Generally accessible   8147 S VINCENNES AVE
..                    ...                    ...
617                   NaN                    NaN
622                   NaN                    NaN
624                   NaN                    NaN
627                   NaN                    NaN
632                   NaN                    NaN
636                   NaN                    NaN
638                   NaN                    NaN
645                   NaN                    NaN
646                   NaN                    NaN
647                   NaN                    NaN
651                   NaN                    NaN
657                   NaN                    NaN

                       Administrator Administrator_Title  \
10                  Juan Carlos Ocon           Principal
11                  Ms. Carrie Spitz            Director
12            Ms.Shannae Bea Jackson           Principal
14                    Tawanna Patton            Director
21               Joyce Dorsey Kenner           Principal
25             Ms.Allison C Tingwall           Principal
29    Mrs.Patricia J Harper Reynolds           Principal
31                   Ms.Mary Bradley            Director
36                   Ms. Brenda Cora            Director
38            Stephanie Yvette Moore           Principal
55                 Ms. Elaine Brooks            Director
56                Sheldon Dion House           Principal
..                               ...                 ...
617                 Ms. Tiara Jordan            Director
622  Mrs.Yashika N Tippett-Eggleston           Principal
624           Ms. Kashawandra Wilson            Director
627               Mary Patricia Beck           Principal
632                  Mr. Eron Powell            Director
636                 Priscilla Horton           Principal
638               Mr.Tyrese L Graham           Principal
645                  Peter J Auffant           Principal
646                   Raul Magdaleno           Principal
647          Mr. Kieran Palmer-Klein            Director
651              Angelica Altamirano           Principal
657             Michael Jerome Biela           Principal

                After_School_Hours Attendance_Boundaries  Average_ACT_School  \
10               2:40 to 8:00 P.M.                     Y                16.5
11                   4:00PM-5:30PM                     N                21.9
12                             NaN                     N                22.5
14                             NaN                     N                17.5
21               3:20 PM - 6:00 PM                     N                27.9
25               3:00 PM - 7:00 PM                     Y                17.4
29               4:00 PM - 7:00 PM                     N                14.6
31                 3:40 PM -5:15PM                     Y                17.2
36                   4:15pm-5:30pm                     N                18.5
38   3:38 p.m. - 6:00  p.m. (M-Th)                     N                15.6
55                             NaN                     N                15.3
56                             NaN                     N                16.2
..                             ...                   ...                 ...
617                            NaN                     N                 NaN
622            03:00 Pm - 06:00 PM                     N                 NaN
624              4:00 PM - 6:00 PM                     N                 NaN
627                 3:15 - 5:30 PM                     Y                 NaN
632              3:30 PM - 5:00 PM                     N                 NaN
636              3:30 PM - 6:00 PM                     N                 NaN
638  3:38 p.m. - 6:00  p.m. (M-Th)                     N                 NaN
645             3:16 PM to 6:00 PM                     Y                 NaN
646                            NaN                     Y                 NaN
647                 3:40PM -5:15PM                     Y                 NaN
651             03:30 PM - 7:00 PM                     Y                 NaN
657          3:30 p.m. - 6:00 p.m.                     N                 NaN

    Bilingual_Services                                 CPS_School_Profile  \
10                   Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
11                   N  http://cps.edu/Schools/Pages/school.aspx?Schoo...
12                   N  http://cps.edu/Schools/Pages/school.aspx?Schoo...
14                   Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
21                   Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
25                   Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
29                   Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
31                   N  http://cps.edu/Schools/Pages/school.aspx?Schoo...
36                   Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
38                   Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
55                   Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
56                   N  http://cps.edu/Schools/Pages/school.aspx?Schoo...
..                 ...                                                ...
617                  Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
622                  N  http://cps.edu/Schools/Pages/school.aspx?Schoo...
624                  N  http://cps.edu/Schools/Pages/school.aspx?Schoo...
627                  Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
632                  Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
636                  Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
638                  Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
645                  Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
646                  Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
647                  N  http://cps.edu/Schools/Pages/school.aspx?Schoo...
651                  Y  http://cps.edu/Schools/Pages/school.aspx?Schoo...
657                  N  http://cps.edu/Schools/Pages/school.aspx?Schoo...

        City                         Classification_Description  \
10   Chicago  Schools that have an attendance boundary. Gene...
11   Chicago  Schools that are open to all Chicago children,...
12   Chicago  Schools that offer a rigorous curriculum with ...
14   Chicago  Schools that are open to all Chicago children,...
21   Chicago  Schools that offer a rigorous curriculum with ...
25   Chicago  Schools that specialize in a specific subject ...
29   Chicago  These schools limit their student populations ...
31   Chicago  Schools that are open to all Chicago children,...
36   Chicago  Schools that are open to all Chicago children,...
38   Chicago  These schools limit their student populations ...
55   Chicago  Schools that are open to all Chicago children,...
56   Chicago  Students receive a college-preparatory curricu...
..       ...                                                ...
617      NaN  Schools that are open to all Chicago children,...
622      NaN  For students who wish to develop leadership an...
624      NaN  Schools that are open to all Chicago children,...
627      NaN  Schools that have an attendance boundary. Gene...
632      NaN  Schools that are open to all Chicago children,...
636      NaN  These schools limit their student populations ...
638      NaN  These schools limit their student populations ...
645      NaN  Schools that have an attendance boundary. Gene...
646      NaN  Schools that have an attendance boundary. Gene...
647      NaN  Schools that are open to all Chicago children,...
651      NaN  Schools that have an attendance boundary. Gene...
657      NaN  For students who wish to develop leadership an...

                                   Classroom_Languages  \
10                                     French, Spanish
11                                    Russian, Spanish
12                                     French, Spanish
14                                             Spanish
21   American Sign Language, Chinese, French, Japan...
25   French, Mandarin, Spanish, Spanish for Heritag...
29                                             Spanish
31                                                 NaN
36              Spanish, Spanish for Heritage Speakers
38              Spanish, Spanish for Heritage Speakers
55                                             Spanish
56                                     French, Spanish
..                                                 ...
617                                            Spanish
622                                    French, Spanish
624                                            Spanish
627     French, Spanish, Spanish for Heritage Speakers
632                                            Spanish
636             Spanish, Spanish for Heritage Speakers
638             Spanish, Spanish for Heritage Speakers
645     French, Spanish, Spanish for Heritage Speakers
646                                   Chinese, Spanish
647                                                NaN
651                                            Spanish
657                                    French, Spanish

     Closed_For_Enrollment_Date  College_Enrollment_Rate_Mean  \
10                          NaN                          57.9
11                          NaN                          57.9
12                          NaN                          57.9
14                          NaN                          57.9
21                          NaN                          57.9
25                          NaN                          57.9
29                          NaN                          57.9
31                          NaN                          57.9
36                          NaN                          57.9
38                          NaN                          57.9
55                          NaN                          57.9
56                          NaN                          57.9
..                          ...                           ...
617                         NaN                          59.8
622                         NaN                          59.8
624                         NaN                          59.8
627                         NaN                          59.8
632                         NaN                          59.8
636                         NaN                          59.8
638                         NaN                          59.8
645                         NaN                          59.8
646                         NaN                          59.8
647                         NaN                          59.8
651                         NaN                          59.8
657                         NaN                          59.8

     College_Enrollment_Rate_School  \
10                             50.6
11                             85.7
12                             85.1
14                             72.7
21                             85.2
25                             65.8
29                             40.0
31                             80.4
36                             76.9
38                             65.4
55                             65.8
56                             63.2
..                              ...
617                            76.0
622                            52.9
624                            86.4
627                            71.6
632                            68.2
636                            43.9
638                            69.4
645                            65.2
646                            54.0
647                            75.9
651                            57.4
657                            62.6

                               Demographic_Description Dress_Code  \
10   The largest demographic at JUAREZ HS is Hispan...          N
11   The largest demographic at NOBLE - PRITZKER HS...          Y
12   The largest demographic at BROOKS HS is Black....          N
14   The largest demographic at EPIC HS is Black.  ...          Y
21   The largest demographic at YOUNG HS is Hispani...          N
25   The largest demographic at CURIE HS is Hispani...          N
29   The largest demographic at AUSTIN CCA HS is Bl...          N
31   The largest demographic at U OF C - WOODLAWN H...          Y
36   The largest demographic at NOBLE - ROWE CLARK ...          Y
38   The largest demographic at UPLIFT HS is Black....          N
55   The largest demographic at NORTH LAWNDALE - CH...          Y
56   The largest demographic at SIMEON HS is Black....          Y
..                                                 ...        ...
617  The largest demographic at NORTH LAWNDALE - CO...          Y
622  The largest demographic at AIR FORCE HS is His...          Y
624  The largest demographic at NOBLE - HANSBERRY H...          Y
627  The largest demographic at SENN HS is Hispanic...          Y
632  The largest demographic at PERSPECTIVES - TECH...          Y
636  The largest demographic at BOWEN HS is Black. ...          Y
638  The largest demographic at UPLIFT HS is Black....          Y
645  The largest demographic at MATHER HS is Hispan...          N
646  The largest demographic at KELLY HS is Hispani...          N
647  The largest demographic at U OF C - WOODLAWN H...          Y
651  The largest demographic at HUBBARD HS is Hispa...          Y
657  The largest demographic at RICKOVER MILITARY H...          Y

                      Earliest_Drop_Off_Time  \
10                                  7:00 A.M
11                                    7:00AM
12                                   6:30 AM
14                                       NaN
21                                   7:00 AM
25                                       NaN
29                                   7:55 AM
31                                   7:30 AM
36                                    7:00am
38                                       NaN
55                                       NaN
56                                      7:15
..                                       ...
617                                      NaN
622                                  7:15 AM
624  7:00 AM (11th/12th); 8:00 AM (9th/10th)
627                                  7:15 AM
632                                      NaN
636                                  7:30 AM
638                                      NaN
645                                  7:30 AM
646                                      NaN
647                                   7:30AM
651                                  6:00 AM
657                                7:15 a.m.

                                              Facebook        Fax  \
10                                                 NaN  7.735e+09
11            https://www.facebook.com/benoblepritzker  7.734e+09
12                                                 NaN  7.735e+09
14      https://www.facebook.com/EPICAcademyHighSchool  7.736e+09
21                      http://www.facebook.com/wmymhs  7.735e+09
25                    https://www.facebook.com/curiehs  7.735e+09
29                                                 NaN  7.735e+09
31            https://www.facebook.com/UCCharterSchool  7.733e+09
36              https://www.facebook.com/BeNobleRCMSA/  7.738e+09
38                                                 NaN  7.735e+09
55                     https://www.facebook.com/nlcphs  7.735e+09
56                                                 NaN  7.735e+09
..                                                 ...        ...
617                    https://www.facebook.com/nlcphs  7.735e+09
622                                                NaN  7.735e+09
624               https://www.facebook.com/BeNobleHCP/  7.733e+09
627  http://www.facebook.com/SennFineArtsMagnetHigh...  7.735e+09
632            https://www.facebook.com/perspectivescs  7.734e+09
636                                                NaN  7.735e+09
638                                                NaN  7.735e+09
645                                                NaN  7.735e+09
646                                                NaN  7.735e+09
647           https://www.facebook.com/UCCharterSchool  7.733e+09
651                                                NaN  7.735e+09
657                                                NaN  7.735e+09

    Fifth_Contact_Name                     Fifth_Contact_Title  Finance_ID  \
10                 NaN                                     NaN       46421
11                 NaN                                     NaN       66142
12                 NaN                                     NaN       47051
14           Dan Grady        Director of Specialized Services       63081
21          Lynn Zalon                     Assistant Principal       47101
25     Homero PeÃ±uelas                     Assistant Principal       53101
29   Mr. Daniel Staley             Tech Coordinator/Programmer       46621
31         Carla Scott                     Admissions Director       66112
36                 NaN                                     NaN       66144
38                 NaN                                     NaN       26861
55                 NaN                                     NaN       66091
56                 NaN                                     NaN       53061
..                 ...                                     ...         ...
617                NaN                                     NaN       66092
622                NaN                                     NaN       45231
624                NaN                                     NaN       66574
627        David Gregg  IB-MYP Coordinator/Admissions Director       47061
632                NaN                                     NaN       66053
636      Karen Stewart                        Dean of Students       46491
638                NaN                                     NaN       26861
645                NaN                                     NaN       46241
646     Andrew Chipman                     Assistant Principal       46181
647        Carla Scott                     Admissions Director       66112
651                NaN                                     NaN       46341
657                NaN                                     NaN       45221

    Fourth_Contact_Name                             Fourth_Contact_Title  \
10     Santiago Marquez                                   IB Coordinator
11                  NaN                                              NaN
12                  NaN                                              NaN
14          Josh Miller                              Assistant Principal
21          Melvin Soto                              Assistant Principal
25       Sussan Oladipo                              Assistant Principal
29     Dr. Erica Jordan                                        Counselor
31    Latasha McMillion                                Operations Manger
36          Conor Quinn                              Assistant Principal
38                  NaN                                              NaN
55                  NaN                                              NaN
56                  NaN                                              NaN
..                  ...                                              ...

In [108]:
df = df[['School_ID','Long_Name','Graduation_Rate_School','Administrator', 'Dress_Code', 
         'Network',
         'Student_Count_Total', 
         'Student_Count_Asian',
         'Student_Count_Asian_Pacific_Islander',
         'Student_Count_Black',
         'Student_Count_English_Learners',
         'Student_Count_Ethnicity_Not_Available',
         'Student_Count_Hawaiian_Pacific_Islander',
         'Student_Count_Hispanic',
         'Student_Count_Low_Income',
         'Student_Count_Multi',
         'Student_Count_Native_American',
         'Student_Count_Other_Ethnicity',
         'Student_Count_Special_Ed',
         'Student_Count_Total',
         'Student_Count_White',
         'Transportation_El',
         'Zip']]

In [109]:
#School ID and Long_Name are identifiers, and do not count.
df.shape

(245, 23)

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 245 entries, 10 to 657
Data columns (total 23 columns):
School_ID                                  245 non-null int64
Long_Name                                  245 non-null object
Graduation_Rate_School                     245 non-null float64
Administrator                              245 non-null object
Dress_Code                                 245 non-null object
Network                                    122 non-null object
Student_Count_Total                        245 non-null int64
Student_Count_Asian                        245 non-null int64
Student_Count_Asian_Pacific_Islander       245 non-null int64
Student_Count_Black                        245 non-null int64
Student_Count_English_Learners             245 non-null int64
Student_Count_Ethnicity_Not_Available      245 non-null int64
Student_Count_Hawaiian_Pacific_Islander    245 non-null int64
Student_Count_Hispanic                     245 non-null int64
Student_Count_Low_Income                   245 non-null int64
Student_Count_Multi                        245 non-null int64
Student_Count_Native_American              245 non-null int64
Student_Count_Other_Ethnicity              245 non-null int64
Student_Count_Special_Ed                   245 non-null int64
Student_Count_Total                        245 non-null int64
Student_Count_White                        245 non-null int64
Transportation_El                          185 non-null object
Zip                                        121 non-null float64
dtypes: float64(2), int64(16), object(5)
memory usage: 45.9+ KB

In [111]:
df['School_ID'].unique()

array([609764, 400054, 609726, 400094, 609755, 609756, 610518, 400077,
       400056, 610394, 400058, 609692, 610529, 610340, 609744, 609738,
       609746, 609712, 400010, 400033, 609691, 609704, 400106, 610245,
       609724, 400064, 400055, 400105, 400104, 609698, 610524, 609728,
       400066, 400086, 610557, 609705, 400051, 609694, 609739, 609761,
       609754, 609748, 400057, 609722, 610547, 609713, 610385, 609720,
       400034, 610381, 609676, 609733, 610383, 609740, 609759, 400085,
       609715, 609734, 400036, 609741, 400052, 610543, 609783, 609730,
       609716, 609762, 610389, 609737, 609723, 609732, 609674, 609718,
       609709, 400035, 609725, 610334, 610391, 609727, 609708, 610323,
       609729, 610513, 610384, 610244, 609749, 609753, 609760, 609693,
       400022, 609680, 610392, 609678, 609719, 400087, 610380, 609750,
       400053, 400062, 610357, 609707, 400098, 610506, 400013, 609679,
       610499, 400061, 609751, 609766, 400032, 609768, 400102, 609695,
       400091, 609710, 609735, 400059, 609682, 609711, 400097, 610304,
       610390, 610558, 400147, 400118, 400115, 400119, 400117])

In [112]:
df['Graduation_Rate_School'].isna().sum()

0

In [113]:
df.sort_values('School_ID')

,School_ID,Long_Name,Graduation_Rate_School,Administrator,Dress_Code,Network,Student_Count_Total,Student_Count_Asian,Student_Count_Asian_Pacific_Islander,Student_Count_Black,Student_Count_English_Learners,Student_Count_Ethnicity_Not_Available,Student_Count_Hawaiian_Pacific_Islander,Student_Count_Hispanic,Student_Count_Low_Income,Student_Count_Multi,Student_Count_Native_American,Student_Count_Other_Ethnicity,Student_Count_Special_Ed,Student_Count_Total,Student_Count_White,Transportation_El,Zip
88,400010,ACE Technical Charter School,68.8,Cecilia Baader,Y,NaN,314,0,0,259,22,0,1,49,302,1,0,0,67,314,4,"Brown, Purple, Red",60609.0
452,400013,ASPIRA Charter School - Early College High School,79.2,Brenda Stolle,Y,Charter,340,2,0,7,108,0,0,323,316,2,1,0,86,340,5,Blue,NaN
558,400013,ASPIRA Charter School - Early College High School,67.9,Brenda Stolle,Y,NaN,378,3,0,12,103,7,0,350,358,1,0,0,95,378,5,Blue,60618.0
491,400022,Chicago High School for the Arts (ChiArts),84.6,Mr. Michael Wang,N,Contract,612,11,0,207,5,38,1,216,193,16,2,0,40,612,121,"Blue, Red",NaN
467,400022,Chicago High School for the Arts (ChiArts),81.1,Mr. Michael Wang,N,NaN,621,15,0,238,5,27,2,202,332,17,1,0,38,621,119,"Blue, Red",60622.0
586,400032,CICS - Ralph Ellison,78.6,Ms. Kimberly Hinton,Y,NaN,425,0,0,417,0,4,0,3,391,1,0,0,80,425,0,Green,60620.0
353,400032,CICS - Ralph Ellison,77.8,Ms. Taquia Hylton,Y,Charter,348,0,0,347,0,0,0,1,298,0,0,0,76,348,0,Green,NaN
98,400033,CICS - Longwood,82.6,Ms. Kenyatta Starks,Y,NaN,1329,0,0,1307,9,8,0,8,1221,4,0,0,230,1329,2,NaN,60643.0
383,400033,CICS - Longwood,73.3,Ms. Angel Johnson,Y,Charter,1281,0,0,1272,13,0,0,8,1050,0,0,0,239,1281,1,NaN,NaN
248,400034,CICS - Northtown,83.3,Torry A. Bennett,Y,NaN,901,141,0,59,114,1,3,483,723,19,7,0,213,901,188,"Blue, Red",60659.0
290,400034,CICS - Northtown,84.4,Torry A. Bennett,Y,Charter,918,165,0,61,134,0,3,514,675,19,3,0,209,918,153,"Blue, Red",NaN
391,400035,Chicago Math and Science Academy Charter School,85.2,Mr. Michael Kuran,Y,NaN,584,54,1,180,82,0,0,317,533,9,3,0,57,584,20,NaN,60626.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,610518,Austin College and Career Academy High School,77.3,Mrs.Simone G. Griffin,N,Network 15,214,0,0,208,1,0,0,3,160,1,1,0,67,214,1,Green,NaN
29,610518,Austin College and Career Academy High School,70.9,Mrs.Patricia J Harper Reynolds,N,NaN,223,0,0,215,3,0,0,5,216,1,1,0,64,223,1,Green,60644.0
423,610524,Louisa May Alcott College Preparatory HS,81.3,Elias Estrada,N,NaN,316,2,0,60,21,0,2,214,209,4,1,0,60,316,33,"Blue, Red",NaN
149,610524,Louisa May Alcott College Preparatory HS,87.1,Elias Estrada,N,NaN,319,5,0,50,20,2,2,223,265,6,1,0,40,319,30,"Blue, Red",60618.0
287,610529,Ogden International High School,93.9,Michael S Beyer,N,NaN,596,18,0,263,15,0,0,220,282,17,2,0,61,596,76,Blue,NaN
58,610529,Ogden International High School,83.6,Michael S Beyer,N,NaN,880,41,0,323,33,0,1,288,481,25,4,0,93,880,198,Blue,60642.0
320,610543,Eric Solorio Academy High School,80.5,Victor Iturralde,Y,NaN,1190,0,0,56,152,1,0,1116,1128,4,4,0,125,1190,9,Orange,60632.0
562,610543,Eric Solorio Academy High School,82.7,Victor Iturralde,Y,AUSL,1196,0,0,50,156,0,0,1128,905,2,7,0,132,1196,9,Orange,NaN
207,610547,South Shore Intl College Prep High School,71.0,Janice Elaine Wells,Y,NaN,651,1,0,624,4,0,0,18,568,8,0,0,58,651,0,Red,60649.0
307,610547,South Shore Intl College Prep High School,86.5,Towanna Butler,Y,Network 17,655,0,0,633,6,0,0,16,507,5,0,0,59,655,1,Red,NaN
166,610557,Pathways in Education- Ashburn,0.0,Mr. Andrew Morgan,N,NaN,227,0,0,62,22,0,0,141,200,1,1,0,27,227,22,NaN,60652.0
190,610558,Sarah E. Goode STEM Academy,92.1,Armando Rodriguez,Y,Network 16,917,2,0,417,73,0,1,481,493,6,3,0,150,917,7,NaN,NaN

In [129]:
df['Zip'].dtype

dtype('float64')

In [160]:
import math
df_nonan_zip = df.dropna(subset = ['Zip'])
for i, row in df.iterrows():
    if math.isnan(row['Zip']):
        correct_zip = df_nonan_zip.loc[df_nonan_zip.School_ID == row['School_ID']]['Zip']
    df.set_value(i, 'Zip', correct_zip)


        
        #print(row[['School_ID', 'Zip']])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

AttributeError: 'BlockManager' object has no attribute 'T'

In [156]:
df.Zip

10     60608.0
11     60639.0
12     60628.0
14     60617.0
21     60607.0
25     60632.0
29     60644.0
31     60637.0
36     60651.0
38     60640.0
55     60623.0
56     60620.0
        ...
617        NaN
622        NaN
624        NaN
627        NaN
632        NaN
636        NaN
638        NaN
645        NaN
646        NaN
647        NaN
651        NaN
657        NaN
Name: Zip, Length: 245, dtype: float64

In [ ]:
#fill in zipcodes
df_zips = df[['School_ID', 'Zip']]
#drop na
df_zips = df_zips.dropna(subset = ['Zip'])
df_zips = df_zips.drop_duplicates(subset = ['Zip'])
#create zip dictionary with school it
zip_dict = df_zips.to_dict()
#zip_dict[11].dtype

In [ ]:
for key,value in df_zips.items():
    df.loc[df.School_ID == key, 'Zip'] = value

In [136]:
zip_dict

{'School_ID': {10: 609764,
  11: 400054,
  12: 609726,
  14: 400094,
  21: 609755,
  25: 609756,
  29: 610518,
  31: 400077,
  36: 400056,
  38: 610394,
  55: 400058,
  56: 609692,
  58: 610529,
  60: 610340,
  63: 609744,
  79: 609738,
  86: 609746,
  87: 609712,
  88: 400010,
  98: 400033,
  114: 400106,
  130: 400064,
  145: 609698,
  149: 610524,
  154: 609728,
  159: 400066,
  177: 609694,
  206: 609722,
  207: 610547,
  267: 609733,
  284: 609740,
  296: 609734,
  329: 609730,
  352: 610389,
  379: 609718,
  416: 610391,
  423: 609708,
  458: 609753,
  460: 609760,
  474: 609680,
  476: 609678,
  490: 609719,
  554: 400098},
 'Zip': {10: 60608.0,
  11: 60639.0,
  12: 60628.0,
  14: 60617.0,
  21: 60607.0,
  25: 60632.0,
  29: 60644.0,
  31: 60637.0,
  36: 60651.0,
  38: 60640.0,
  55: 60623.0,
  56: 60620.0,
  58: 60642.0,
  60: 60634.0,
  63: 60659.0,
  79: 60614.0,
  86: 60615.0,
  87: 60619.0,
  88: 60609.0,
  98: 60643.0,
  114: 60621.0,
  130: 60616.0,
  145: 60652.0,
  149: 60618.0,
  154: 60625.0,
  159: 60653.0,
  177: 60629.0,
  206: 60612.0,
  207: 60649.0,
  267: 60626.0,
  284: 60622.0,
  296: 60631.0,
  329: 60660.0,
  352: 60624.0,
  379: 60638.0,
  416: 60636.0,
  423: 60641.0,
  458: 60655.0,
  460: 60627.0,
  474: 60610.0,
  476: 60605.0,
  490: 60613.0,
  554: 60602.0}}

In [114]:
#Charter or not, #programs offered (chess) - count of programs offered
#scrape name of Principal
#create new Principal field based on gender.
#do I start out with this data subset?
#scrape demographic for year
#can take out specific columns that are too predictive, such as low income,
#in order to show how much affect some features have
#put in attendance